// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxlJe1ZCO2VoCzuk0UCcvmiWsWJwchwso',
    appId: '1:811643579235:web:201aeba9945098d7a78156',
    messagingSenderId: '811643579235',
    projectId: 'notlar-ad634',
    authDomain: 'notlar-ad634.firebaseapp.com',
    storageBucket: 'notlar-ad634.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrmb2XByYEoj-QWI4MGxQT74fxtegP6QY',
    appId: '1:811643579235:android:0ab68f5314fa2fb1a78156',
    messagingSenderId: '811643579235',
    projectId: 'notlar-ad634',
    storageBucket: 'notlar-ad634.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV_6zN9YlJeuTbjvwMOfhL8OT7Hx-iSJQ',
    appId: '1:811643579235:ios:e7af6c27188322a1a78156',
    messagingSenderId: '811643579235',
    projectId: 'notlar-ad634',
    storageBucket: 'notlar-ad634.appspot.com',
    iosClientId: '811643579235-vucluqb66ht6mh0ib1ui5ui7jol331a1.apps.googleusercontent.com',
    iosBundleId: 'com.mobilemastermind.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV_6zN9YlJeuTbjvwMOfhL8OT7Hx-iSJQ',
    appId: '1:811643579235:ios:43df92207463cb20a78156',
    messagingSenderId: '811643579235',
    projectId: 'notlar-ad634',
    storageBucket: 'notlar-ad634.appspot.com',
    iosClientId: '811643579235-pfmmiuqpgpkmfiuuevbmd3k25ikebiu1.apps.googleusercontent.com',
    iosBundleId: 'com.mobilemastermind.notes.RunnerTests',
  );
}
